name: click_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  # manage statement & local  storage
  get: ^4.6.5
  get_storage: ^2.0.3
  #value equality
  equatable: ^2.0.3
  # function programing thinking
  dartz: ^0.10.1
  # tools & custom ui
  flutter_launcher_icons: ^0.9.3
  google_fonts: 3.0.1
  flutter_svg: ^1.1.0
  lazy_load_scrollview: ^1.3.0
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.2.1
  extended_image: ^6.2.1
  carousel_slider: ^4.1.1
  gallery_saver: ^2.3.2
  # network
  connectivity_plus: ^2.3.0
  url_launcher: ^6.1.2
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.14.4
  mockito: ^5.2.0

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/click_logo_new.png"

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/logo/
